spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / update / validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
